### ISSUE TITLE
vlc 无法播放udp流 udp/h264://@:8880

### ISSUE THREAD

**Issue by junjunsay** [YueChen-C/ios-screen-record#1]
1.运行 ioscreen --udid=xxxx udp
2.vlc 输入网址 udp/h264://@:8880
3.vlc 依旧白屏，无视频流播放

**Comment by YueChen-C** [comment]
1.能录制 h264 吗？
2.如果想用 vlc 测试的话，vlc 需要先处于播放这个地址的状态，然后再启动命令
