### ISSUE TITLE
录制ios手机，会导致手机上没有声音

### ISSUE THREAD

**Issue by ojo909023661** [YueChen-C/ios-screen-record#17]
这个是不是usbWrite的时候同时获取了音频和视频呢？我们希望保留手机上的声音，是不是可以通过修改这里的PingPacketMagic来修改获取的内容呢？但是苦于没有文档，求助
![image](https://github.com/YueChen-C/ios-screen-record/assets/55180680/33cfbb73-dd4a-44bc-b699-470fbb25b860)

**Comment by YueChen-C** [comment]
可以试着注释掉 HPA1 的发送看看
