### ISSUE TITLE
若udid 中含有符号 - 则提示找不到手机，ioscreen -u 694a32 udp运行，提示超时并关闭程序

### ISSUE THREAD

**Issue by junjunsay** [YueChen-C/ios-screen-record#2]
1.(testdevice) MacBook-Pro ~ % ioscreen -u 694a32 udp
 - util.py[line:58] - INFO: Find Device UDID: 694a32
- consumer.py[line:100] - INFO: listen UDP: udp/h264://127.0.0.1:8880
 - util.py[line:91] - INFO: Disabling hidden QT config
- util.py[line:152] - INFO: enable_qt_config..
 - util.py[line:71] - INFO: Enabling hidden QT config
 - util.py[line:58] - INFO: Find Device UDID: 694a32
 - util.py[line:175] - INFO: USB connection ready, waiting for ping..
 - meaasge.py[line:148] - INFO: AudioVideo-Stream has start success
 - util.py[line:190] - WARNING: [Errno 60] Operation timed out
 - meaasge.py[line:159] - INFO: Telling device to stop streaming..
 - util.py[line:91] - INFO: Disabling hidden QT config
 手机运行ioscreen -u 694a32 udp ，AudioVideo-Stream提示成功，过几秒后，提示超时，程序自动关闭
2.若udid 中含有符号 - 则提示找不到手机

**Comment by YueChen-C** [comment]
1. AudioVideo-Stream has start success 这个证明通道建立成功了，成功接收到了 ping 数据，超时应该是回传数据没回调了，有没有开什么代理转移了 usbmuxx 之类的
2.se 现在识别是有问题，去掉 - 也可以识别
