### ISSUE TITLE
这个工具能支持在Windows连接iPhone场景下录屏吗

### ISSUE THREAD

**Issue by linmscat** [YueChen-C/ios-screen-record#3]
执行：pip install ioscreen，出现以下错误：
Building wheel for PyGObject (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'F:\GitLab\apprunner\venv\Scripts\python.exe' 'F:\GitLab\apprunner\venv\lib\site-packages\pip\_ven
dor\pep517\_in_process.py' build_wheel 'D:\Users\yl1150\AppData\Local\Temp\tmpg86y3yx1'
       cwd: D:\Users\yl1150\AppData\Local\Temp\pip-install-ia3oem36\pygobject_e138554edb0d49deb98def802edfefc4

  Complete output (42 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.8
  creating build\lib.win-amd64-3.8\pygtkcompat
  copying pygtkcompat\generictreemodel.py -> build\lib.win-amd64-3.8\pygtkcompat
  copying pygtkcompat\pygtkcompat.py -> build\lib.win-amd64-3.8\pygtkcompat
  copying pygtkcompat\__init__.py -> build\lib.win-amd64-3.8\pygtkcompat
  creating build\lib.win-amd64-3.8\gi
  copying gi\docstring.py -> build\lib.win-amd64-3.8\gi
  copying gi\importer.py -> build\lib.win-amd64-3.8\gi
  copying gi\module.py -> build\lib.win-amd64-3.8\gi
  copying gi\pygtkcompat.py -> build\lib.win-amd64-3.8\gi
  copying gi\types.py -> build\lib.win-amd64-3.8\gi
  copying gi\_constants.py -> build\lib.win-amd64-3.8\gi
  copying gi\_error.py -> build\lib.win-amd64-3.8\gi
  copying gi\_gtktemplate.py -> build\lib.win-amd64-3.8\gi
  copying gi\_option.py -> build\lib.win-amd64-3.8\gi
  copying gi\_ossighelper.py -> build\lib.win-amd64-3.8\gi
  copying gi\_propertyhelper.py -> build\lib.win-amd64-3.8\gi
  copying gi\_signalhelper.py -> build\lib.win-amd64-3.8\gi
  copying gi\__init__.py -> build\lib.win-amd64-3.8\gi
  creating build\lib.win-amd64-3.8\gi\repository
  copying gi\repository\__init__.py -> build\lib.win-amd64-3.8\gi\repository
  creating build\lib.win-amd64-3.8\gi\overrides
  copying gi\overrides\Gdk.py -> build\lib.win-amd64-3.8\gi\overrides
  copying gi\overrides\GdkPixbuf.py -> build\lib.win-amd64-3.8\gi\overrides
  copying gi\overrides\GIMarshallingTests.py -> build\lib.win-amd64-3.8\gi\overrides
  copying gi\overrides\Gio.py -> build\lib.win-amd64-3.8\gi\overrides
  copying gi\overrides\GLib.py -> build\lib.win-amd64-3.8\gi\overrides
  copying gi\overrides\GObject.py -> build\lib.win-amd64-3.8\gi\overrides
  copying gi\overrides\Gtk.py -> build\lib.win-amd64-3.8\gi\overrides
  copying gi\overrides\keysyms.py -> build\lib.win-amd64-3.8\gi\overrides
  copying gi\overrides\Pango.py -> build\lib.win-amd64-3.8\gi\overrides
  copying gi\overrides\__init__.py -> build\lib.win-amd64-3.8\gi\overrides
  running build_ext
  pycairo: new API
  pycairo: trying include directory: 'D:\\Users\\yl1150\\AppData\\Local\\Temp\\pip-build-env-46pn1i2p\\overlay
\\Lib\\site-packages\\cairo\\include'
  pycairo: found 'D:\\Users\\yl1150\\AppData\\Local\\Temp\\pip-build-env-46pn1i2p\\overlay\\Lib\\site-packages
\\cairo\\include\\py3cairo.h'
  building 'gi._gi' extension
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://vi
sualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for PyGObject
Failed to build PyGObject
ERROR: Could not build wheels for PyGObject which use PEP 517 and cannot be installed directly

**Comment by linmscat** [comment]
@YueChen-C

**Comment by YueChen-C** [comment]
@linmscat 目前还不可以，windows 上无法激活 usb 端口，我也在看
