### ISSUE TITLE
gstreamer 渲染显示画面命令报错

### ISSUE THREAD

**Issue by suzhenyu006** [YueChen-C/ios-screen-record#4]
报错信息：
![image](https://user-images.githubusercontent.com/38517127/113385911-a452f680-93bb-11eb-862c-557ab11802cf.png)

执行命令：
ioscreen --udid=00008020-000E08CC1A38002E gstreamer
报错说找不到设备，后来看了下issue，把-删除变成这样：
ioscreen --udid=00008020000E08CC1A38002E gstreamer
依旧报错如上图

**Comment by YueChen-C** [comment]
日志全一点吧，只能看到 set_property("sync", False) 异常，但是看不到什么原因呀

**Comment by suzhenyu006** [comment]
@YueChen-C 已经解决了，好像是brew install时，落下了一个库，多谢~~
