### ISSUE TITLE
楼主没遇到gstreamer crash吗？

### ISSUE THREAD

**Issue by prife** [YueChen-C/ios-screen-record#6]
MacOS 15.7

quicktime_hack项目，,/qth gstreamer的话，gstreamer大概率会crash的

**Comment by YueChen-C** [comment]
@prife 增加环境变量查看下 gstreamer  log 吧，没 log 谁也不知道啥问题
python 示例：
```
os.putenv('GST_DEBUG_NO_COLOR', "1")
os.putenv('GST_DEBUG_FILE','./debug.log')
os.putenv('GST_DEBUG','5') ## debug 等级
```

**Comment by prife** [comment]
$ ./quicktime_video_hack gstreamer
{"level":"info","msg":"no usbSerial specified, using '8a8358e12e0306cc804f4367d9152fb795e3b561'","time":"2021-04-19T17:12:21+08:00"}
{"level":"info","msg":"Starting Gstreamer..","time":"2021-04-19T17:12:22+08:00"}
[1]    37586 illegal hardware instruction  ./quicktime_video_hack gstreamer


可以参考：https://github.com/danielpaulus/quicktime_video_hack/issues/78
复现的概率非常高

**Comment by YueChen-C** [comment]
确实挺高的，看起来像他 github.com/danielpaulus/gst 这个库有点问题 gst PLAYING 指令总是无法启动成功，你去给他提个 issues 试试吧

**Comment by prife** [comment]
> 确实挺高的，看起来像他 github.com/danielpaulus/gst 这个库有点问题 gst PLAYING 指令总是无法启动成功，你去给他提个 issues 试试吧

bug不像是gst库，是gstreamer库的mac版本有bug。
我用Qt+ffmpeg重写了显示端，不用gstreamer，问题就没有了。发这个issue只是看到楼主你在testerhome上的帖子，新号无法评论，所以这里建个bug跟你反馈下。
